version: '3.8'
services:
  postgres-softsec:
    container_name: postgres-softsec
    image: postgres
    environment:
      POSTGRES_USER: dbsoftsec
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: softsec
      PGDATA: /data/postgres
    volumes:
      - postgres-softsec:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres-softsec: